os: linux
dist: bionic
sudo: required
language: cpp
cache: ccache
compiler:
  - gcc

git:
  depth: 1

before_install:
  - sudo apt-get -qq install qt5-default qtbase5-dev qtbase5-dev-tools
  - sudo apt-get -qq install libtelepathy-glib-dev libtelepathy-farstream-dev libdbus-c++-dev
  - sudo apt-get -qq install python3-dbus python3-dbus.mainloop.pyqt5

before_script:
  - mkdir ../build-telepathy-qt; cd ../build-telepathy-qt
  - cmake ../telepathy-qt

script:
  - cmake --build . -- -j3 -k
  - CTEST_OUTPUT_ON_FAILURE=1 ctest --force-new-ctest-process

notifications:
  email: false
